### ISSUE TITLE
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'

### ISSUE THREAD

**Issue by sun-rabbit** [jmaple12/speech_to_speech#1]
博主你好，我尝试跑了你的inference_maple0306fix.py，我的text代码如下
`import sys
import pyaudio
sys.path.insert(0, 'GPT-SoVITS-Inference')

from inference_maple0306fix import handle
import warnings
warnings.filterwarnings("ignore")
import sys

text = '''在社会发展过程中，科技与社会总是相互作用、相互交织。科技有其优越性，但依然不足以让社会听命于它；社会也有一些优先性，但不足以完全束缚科学的自由性。
'''

#语音合成模型初始化
ref_wav_path=r"D:\ziliao\sovits\GPT-SoVITS-Inference\trained\胡桃(测试)\我说白术，你不会看不出来吧？难不成你师父，忘了教你这门功夫？.wav"
prompt_text= '我说白术，你不会看不出来吧？难不成你师父，忘了教你这门功夫？。'
prompt_language='zh'
text=text#'你好呀！'
text_language='zh'
ref_free=False
stream=False
start=False
top_k=5
top_p=1
temperature=1
sovits_path = r"D:\ziliao\sovits\GPT-SoVITS-Inference\trained\胡桃(测试)\hutao_e60_s3360.pth"
gpt_path = r"D:\ziliao\sovits\GPT-SoVITS-Inference\trained\胡桃(测试)\hutao-e75.ckpt"

#音频直接播放
if not stream:
    handle(ref_wav_path, prompt_text, prompt_language, text, text_language, sovits_path, gpt_path, start=start, top_k=top_k, top_p=top_p,temperature=temperature, ref_free = ref_free, stream=False)
    #流式音频---输出快了一些，但是中间有停顿
else:
    handle(ref_wav_path, prompt_text, prompt_language, text, text_language, sovits_path, gpt_path, start=start, top_k=top_k, top_p=top_p,temperature=temperature, ref_free = ref_free, stream=True)
#10min40s`，但是总是会出现  return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'
这样子的错误，我已经升级的torch版本，但是并没有解决，请问可以给点指导吗

**Comment by sun-rabbit** [comment]
![@J UVCBN3IV7EK7UTD88(_8](https://github.com/jmaple12/speech_to_speech/assets/114917342/8280b9f1-f0fe-4b6d-bd97-2faa49f5235e)

**Comment by jmaple12** [comment]
> 博主你好，我尝试跑了你的inference_maple0306fix.py，我的text代码如下 `import sys import pyaudio sys.path.insert(0, 'GPT-SoVITS-Inference')
> 
> from inference_maple0306fix import handle import warnings warnings.filterwarnings("ignore") import sys
> 
> text = '''在社会发展过程中，科技与社会总是相互作用、相互交织。科技有其优越性，但依然不足以让社会听命于它；社会也有一些优先性，但不足以完全束缚科学的自由性。 '''
> 
> #语音合成模型初始化 ref_wav_path=r"D:\ziliao\sovits\GPT-SoVITS-Inference\trained\胡桃(测试)\我说白术，你不会看不出来吧？难不成你师父，忘了教你这门功夫？.wav" prompt_text= '我说白术，你不会看不出来吧？难不成你师父，忘了教你这门功夫？。' prompt_language='zh' text=text#'你好呀！' text_language='zh' ref_free=False stream=False start=False top_k=5 top_p=1 temperature=1 sovits_path = r"D:\ziliao\sovits\GPT-SoVITS-Inference\trained\胡桃(测试)\hutao_e60_s3360.pth" gpt_path = r"D:\ziliao\sovits\GPT-SoVITS-Inference\trained\胡桃(测试)\hutao-e75.ckpt"
> 
> #音频直接播放 if not stream: handle(ref_wav_path, prompt_text, prompt_language, text, text_language, sovits_path, gpt_path, start=start, top_k=top_k, top_p=top_p,temperature=temperature, ref_free = ref_free, stream=False) #流式音频---输出快了一些，但是中间有停顿 else: handle(ref_wav_path, prompt_text, prompt_language, text, text_language, sovits_path, gpt_path, start=start, top_k=top_k, top_p=top_p,temperature=temperature, ref_free = ref_free, stream=True) #10min40s`，但是总是会出现 return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled) RuntimeError: "LayerNormKernelImpl" not implemented for 'Half' 这样子的错误，我已经升级的torch版本，但是并没有解决，请问可以给点指导吗

在第96行后面写一个is_half=False试一试行不行。

下面是检查torch是否是GPU版本：
import torch
torch.cuda.is_available()看看有没有gpu版本的torch，True是有。
用torch.__version__ 查看torch和cuda版本，如果没有需要再pytorch官网下载。
网上也有下载pytorch的教程

**Comment by sun-rabbit** [comment]
> > 博主你好，我尝试跑了你的inference_maple0306fix.py，我的text代码如下 `import sys import pyaudio sys.path.insert(0, 'GPT-SoVITS-Inference')
> > from inference_maple0306fix import handle import warnings warnings.filterwarnings("ignore") import sys
> > text = '''在社会发展过程中，科技与社会总是相互作用、相互交织。科技有其优越性，但依然不足以让社会听命于它；社会也有一些优先性，但不足以完全束缚科学的自由性。 '''
> > #语音合成模型初始化 ref_wav_path=r"D:\ziliao\sovits\GPT-SoVITS-Inference\trained\胡桃(测试)\我说白术，你不会看不出来吧？难不成你师父，忘了教你这门功夫？.wav" prompt_text= '我说白术，你不会看不出来吧？难不成你师父，忘了教你这门功夫？。' prompt_language='zh' text=text#'你好呀！' text_language='zh' ref_free=False stream=False start=False top_k=5 top_p=1 temperature=1 sovits_path = r"D:\ziliao\sovits\GPT-SoVITS-Inference\trained\胡桃(测试)\hutao_e60_s3360.pth" gpt_path = r"D:\ziliao\sovits\GPT-SoVITS-Inference\trained\胡桃(测试)\hutao-e75.ckpt"
> > #音频直接播放 if not stream: handle(ref_wav_path, prompt_text, prompt_language, text, text_language, sovits_path, gpt_path, start=start, top_k=top_k, top_p=top_p,temperature=temperature, ref_free = ref_free, stream=False) #流式音频---输出快了一些，但是中间有停顿 else: handle(ref_wav_path, prompt_text, prompt_language, text, text_language, sovits_path, gpt_path, start=start, top_k=top_k, top_p=top_p,temperature=temperature, ref_free = ref_free, stream=True) #10min40s`，但是总是会出现 return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled) RuntimeError: "LayerNormKernelImpl" not implemented for 'Half' 这样子的错误，我已经升级的torch版本，但是并没有解决，请问可以给点指导吗
> 
> 在第96行后面写一个is_half=False试一试行不行。
> 
> 下面是检查torch是否是GPU版本： import torch torch.cuda.is_available()看看有没有gpu版本的torch，True是有。 用torch.**version** 查看torch和cuda版本，如果没有需要再pytorch官网下载。 网上也有下载pytorch的教程

感谢，是我换了个新电脑环境没有配置完全。
